name: Run benchmarks

on:
  issues:
    types: [opened]
      
jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'RUN BENCHMARK')
    steps:
    - name: Accept the task
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-id: ${{ github.event.issue.id }}  
        body: |
          Serving the benchmark. I will update the issue when it's finished. 
    - uses: actions/checkout@v2
    - name: Build images
      run: ./build.sh
    - name: Run tests
      id: run_bench
      run: echo "::set-output name=results::$(./bench.sh)\n"
      env:
        GRPC_BENCHMARK_DURATION: ${{github.event.issue.body}}
    - name: Close Issue
      uses: peter-evans/close-issue@v1
      with:
        comment: |
          Here you go!
          ```
          ${{ steps.run_bench.outputs.results }}
          ```
          
